INFO:root:Aplicativo iniciado
INFO:werkzeug: * Running on http://localhost:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:werkzeug: * Detected change in 'c:\\Users\\Admin\\Desktop\\Leonardo Worm\\Testes\\Flask teste\\open_port_checker.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:werkzeug: * Detected change in 'c:\\Users\\Admin\\Desktop\\Leonardo Worm\\Testes\\Flask teste\\open_port_checker.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
INFO:werkzeug: * Running on http://localhost:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:root:Aplicativo iniciado
INFO:werkzeug: * Running on http://localhost:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:08:57] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:08:57] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:08:57] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:08:57] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:08:57] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:root:Servidor Flask iniciado na porta 5001
INFO:root:Servidor Flask iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:werkzeug: * Running on http://localhost:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:17] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:17] "GET /static/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:17] "GET /static/reset.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:19] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:19] "[36mGET /static/reset.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:10:19] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Admin\\Desktop\\Leonardo Worm\\Testes\\Flask teste\\app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 113-951-105
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:03] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:03] "GET /static/reset.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:03] "GET /static/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:03] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:12] "POST /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:12] "[36mGET /static/reset.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:12] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:15] "GET /register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:15] "[36mGET /static/reset.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:27] "[36mGET /static/reset.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:27] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [16/Oct/2023 15:11:29] "[31m[1mGET /shutdown HTTP/1.1[0m" 405 -
INFO:werkzeug: * Detected change in 'C:\\Users\\Admin\\Desktop\\Leonardo Worm\\Testes\\Flask teste\\app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5001
INFO:root:Servidor Flask iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 114, in register
    new_user = User(username.lower().strip(), password.lower().strip())
TypeError: __init__() takes 1 positional argument but 3 were given
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 114, in register
    new_user = User(username.lower().strip(), password.lower().strip())
TypeError: __init__() takes 1 positional argument but 3 were given
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 98, in login
    user = User.query.filter_by(username).first()
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 116, in register
    new_user = User(username, password)
TypeError: __init__() takes 1 positional argument but 3 were given
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 118, in register
    new_user = User(username, password)
TypeError: __init__() takes 1 positional argument but 3 were given
ERROR:app:Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 118, in register
    new_user = User(username, password)
TypeError: __init__() takes 1 positional argument but 3 were given
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 99, in login
    user = User.query.filter_by(username).first()
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\venv\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\praus\Desktop\Trabalhos\Eu\Programacao\flaskteste\app.py", line 104, in login
    raise ValidationError("Username and password do not match!")
wtforms.validators.ValidationError: Username and password do not match!
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
INFO:root:Aplicativo iniciado
INFO:root:Servidor Gevent iniciado na porta 5000
